"""empty message

Revision ID: fba6041ddfa7
Revises: ff74defebafd
Create Date: 2022-11-10 12:25:08.764322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba6041ddfa7'
down_revision = 'ff74defebafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint("email", 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email", 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
